"""Tests for the sitemap of published datasets.

Links into the app are generated by JavaScript, so a crawler that does not
execute it cannot discover a single published dataset by following links, see
https://github.com/ContactEngineering/topobank-publication/issues/21.
"""

from xml.etree.ElementTree import fromstring

import pytest
from django.urls import reverse
from topobank.testing.factories import (SurfaceFactory, Topography1DFactory,
                                        UserFactory)

from topobank_publication.models import Publication, PublicationCollection
from topobank_publication.sitemap_views import SITEMAP_NAMESPACE

NS = {"sm": SITEMAP_NAMESPACE}


def _urls(response):
    """Return the (loc, lastmod, changefreq) triples of a sitemap response."""
    root = fromstring(response.content)
    return [
        (
            url.find("sm:loc", NS).text,
            url.find("sm:lastmod", NS).text,
            url.find("sm:changefreq", NS).text,
        )
        for url in root.findall("sm:url", NS)
    ]


@pytest.mark.django_db
def test_sitemap_is_valid_xml_in_the_sitemap_namespace(client, example_pub):
    response = client.get(reverse("publication:sitemap"))

    assert response.status_code == 200
    assert response["Content-Type"] == "application/xml"
    root = fromstring(response.content)
    assert root.tag == f"{{{SITEMAP_NAMESPACE}}}urlset"


@pytest.mark.django_db
def test_publication_is_listed_with_absolute_url_and_date(client, example_pub):
    response = client.get(reverse("publication:sitemap"))

    location, last_modified, change_frequency = _urls(response)[0]
    assert location == "http://testserver" + example_pub.get_absolute_url()
    assert last_modified == example_pub.datetime.strftime("%Y-%m-%d")
    # A published dataset is immutable.
    assert change_frequency == "never"


@pytest.mark.django_db
def test_all_publications_are_listed(client, db, example_authors, settings):
    settings.MIN_SECONDS_BETWEEN_SAME_SURFACE_PUBLICATIONS = None
    user = UserFactory()
    publications = []
    for name in ["First", "Second", "Third"]:
        surface = SurfaceFactory(created_by=user, name=name)
        Topography1DFactory(surface=surface)
        publications.append(
            Publication.publish(surface, "cc0-1.0", user, example_authors)
        )

    response = client.get(reverse("publication:sitemap"))

    locations = [location for location, _, _ in _urls(response)]
    assert len(locations) == 3
    for publication in publications:
        assert "http://testserver" + publication.get_absolute_url() in locations


@pytest.mark.django_db
def test_collections_are_listed(client, example_pub):
    collection = PublicationCollection.objects.create(
        title="A collection",
        publisher=example_pub.publisher,
        unique_hash="test-hash",
        short_url="coll1",
    )
    collection.publications.set([example_pub])

    response = client.get(reverse("publication:sitemap"))

    locations = [location for location, _, _ in _urls(response)]
    assert "http://testserver" + reverse(
        "publication:go-collection", kwargs={"short_url": "coll1"}
    ) in locations


@pytest.mark.django_db
def test_objects_without_a_short_url_are_skipped(client, example_pub):
    """A short URL is assigned by a signal; without one there is no URL."""
    example_pub.short_url = None
    example_pub.save()

    response = client.get(reverse("publication:sitemap"))

    assert _urls(response) == []


@pytest.mark.django_db
def test_empty_sitemap_is_still_valid(client, db):
    response = client.get(reverse("publication:sitemap"))

    assert response.status_code == 200
    assert _urls(response) == []


@pytest.mark.django_db
def test_sitemap_route_is_not_shadowed_by_the_go_route(client, db):
    """`sitemap.xml` must not be read as a short URL."""
    assert reverse("publication:sitemap").endswith("/sitemap.xml")
    assert client.get(reverse("publication:sitemap")).status_code == 200
