"""
Sitemap of the published datasets.

Published datasets are only reachable through the single-page app, whose links
are generated by JavaScript. A crawler that does not execute JavaScript can
therefore not discover a single published dataset by following links. The
sitemap lists them explicitly.

This is written out by hand rather than with `django.contrib.sitemaps`, because
that app is not installed in the surrounding project and requiring it would make
this plugin depend on a change to the project's settings.

See https://www.sitemaps.org/protocol.html.
"""

from xml.etree.ElementTree import Element, SubElement, tostring

from django.http import HttpResponse
from django.urls import reverse

from .models import Publication, PublicationCollection

SITEMAP_NAMESPACE = "http://www.sitemaps.org/schemas/sitemap/0.9"

# A single sitemap file may not list more than 50,000 URLs. Splitting into
# several files plus a sitemap index only becomes necessary beyond that, which
# is far above the current number of publications.
MAX_URLS = 50000


def _add_url(parent, location, last_modified):
    url = SubElement(parent, "url")
    SubElement(url, "loc").text = location
    SubElement(url, "lastmod").text = last_modified.strftime("%Y-%m-%d")
    # A published dataset is immutable, so it will never change again.
    SubElement(url, "changefreq").text = "never"


def _entries():
    """Yield (path, last modified) of every published dataset and collection.

    Objects whose short URL has not been assigned yet are skipped: there is no
    URL to list for them.
    """
    for publication in Publication.objects.exclude(short_url=None).order_by(
        "datetime"
    ):
        yield (
            reverse("publication:go", kwargs={"short_url": publication.short_url}),
            publication.datetime,
        )
    for collection in PublicationCollection.objects.exclude(short_url=None).order_by(
        "datetime"
    ):
        yield (
            reverse(
                "publication:go-collection",
                kwargs={"short_url": collection.short_url},
            ),
            collection.datetime,
        )


def sitemap_view(request):
    """Serve the sitemap of all published datasets and collections."""
    root = Element("urlset", {"xmlns": SITEMAP_NAMESPACE})

    for index, (path, last_modified) in enumerate(_entries()):
        if index >= MAX_URLS:
            break
        _add_url(root, request.build_absolute_uri(path), last_modified)

    return HttpResponse(
        tostring(root, encoding="utf-8", xml_declaration=True),
        content_type="application/xml",
    )
