# Generated by Django 4.2.19 on 2025-05-05 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0013_alter_publication_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=10, null=True, unique=True)),
                ('publisher_orcid_id', models.CharField(default='', max_length=19)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('doi_name', models.CharField(default='', max_length=50)),
                ('doi_state', models.CharField(choices=[('draft', 'only visible in Fabrica, DOI can be deleted'), ('registered', 'registered with the DOI Resolver, cannot be deleted'), ('findable', 'registered with the DOI Resolver and indexed in DataCite Search, cannot be deleted')], default='', max_length=10)),
                ('publications', models.ManyToManyField(related_name='publication_collection', to='publication.publication')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
