# Generated by Django 4.2.19 on 2025-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0014_publicationcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcollection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicationcollection',
            name='title',
            field=models.CharField(default='collection default name', max_length=80),
            preserve_default=False,
        ),
    ]
